stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py .\data\raw\raw_movies.csv .\data\raw\tmdb_5000_credits.csv
    deps:
      - .\data\raw\tmdb_5000_movies.csv
      - .\data\raw\tmdb_5000_credits.csv
      - .\src\data\make_dataset.py
    outs:
      - data/processed/processed_movies.csv

  features_movies:
    cmd: python .\src\features\build_features.py .\data\processed\processed_movies.csv
    deps:
      - .\data\processed\processed_movies.csv
      - .\src\features\build_features.py
    outs:
      - data/processed/features_movies.csv

  train_model:
    cmd: python .\src\models\train_model.py .\data\processed\features_movies.csv
    deps:
      - .\data\processed\features_movies.csv
      - .\src\models\train_model.py
    outs:
      - models/movie_dict.pkl 
      - models/similarity.pkl

  predict_model:
    cmd: python .\src\models\predict_model.py 
    deps:
      - .\data\processed\features_movies.csv
      - .\models\movie_dict.pkl
      - .\models\similarity.pkl

  visualize:
    cmd: python .\src\visualization\visualize.py .\data\processed\features_movies.csv
    deps:
      - .\data\processed\features_movies.csv
      - .\src\visualization\visualize.py
